package main

import (
	"flag"
	"fmt"
	"gowacc/ast"
	"os"
	"path"
	"strings"
)

func main() {
	parseOnly := flag.Bool("parse", false, "Parse the file for syntax and symantic errors and generate an AST.")
	printTree := flag.Bool("ast", false, "Display AST generated by the parser.")
	symbolTable := flag.Bool("table", false, "Displays the symbol table generated by the semantic analysis.")
	debugMode := flag.Bool("debug", false, "Print out additional debugging information during compilation.")
	filepath := os.Args[len(os.Args)-1]
	flag.Parse()
	if *debugMode {
		ast.DEBUG_MODE = true
	}
	var tree interface{}
	if len(os.Args) > 1 {
		fmt.Println("-- Compiling...")
		var err error
		tree, err = ParseFile(filepath)
		if err != nil {
			fmt.Println("Errors detected during compilation! Exit code 100 returned.")
			fmt.Println(err)
			os.Exit(100)
		}
	} else {
		fmt.Println("Error: No file provided")
	}
	if !*parseOnly {
		checker := ast.NewSemanticCheck()
		ast.Walk(checker, tree)

		// Print out all errors that occur
		if len(checker.Errors) > 0 {
			fmt.Println("Errors detected during compilation! Exit code 200 returned.")
			checker.PrintErrors(filepath)
			os.Exit(200)
		}
		if *symbolTable {
			checker.PrintSymbolTable()
		}
	}
	if *printTree {
		fmt.Println("-- Printing AST...")
		fmt.Print(strings.TrimSuffix(path.Base(filepath), ".wacc"))
		fmt.Println(".ast contents are:")
		fmt.Println("===========================================================")
		fmt.Print(tree)
		fmt.Println("===========================================================")
	}
	fmt.Println("-- Finished")
}
